// generated by @marwajs/compiler
export const routes = [
  { path: "/-layout", component: (await import("./../pages/_layout.marwa")).default, meta: (await import("./../pages/_layout.marwa")).__route || {} },
  { path: "/settings", component: (await import("./../pages/Settings.marwa")).default, meta: (await import("./../pages/Settings.marwa")).__route || {} },
  { path: "/login", component: (await import("./../pages/Login.marwa")).default, meta: (await import("./../pages/Login.marwa")).__route || {} },
  { path: "/", component: (await import("./../pages/Index.marwa")).default, meta: (await import("./../pages/Index.marwa")).__route || {} },
  { path: "/feature", component: (await import("./../pages/Feature.marwa")).default, meta: (await import("./../pages/Feature.marwa")).__route || {} },
  { path: "/dashboard", component: (await import("./../pages/Dashboard.marwa")).default, meta: (await import("./../pages/Dashboard.marwa")).__route || {} },
  { path: "/about", component: (await import("./../pages/About.marwa")).default, meta: (await import("./../pages/About.marwa")).__route || {} },
  { path: "/404", component: (await import("./../pages/404.marwa")).default, meta: (await import("./../pages/404.marwa")).__route || {} },
] as const;