import { createApp, createRouter } from '@marwajs/core';

/* @marwa:routes:start */
//
// AUTO-GENERATED by @marwajs/compiler — DO NOT EDIT
//
const __MARWA_HISTORY = "browser";
const __MARWA_ROUTES:any = [
  // CLI injects routes here, e.g.:
  // { path: "/", loader: () => import("./pages/Index.marwa"), layouts: [] },
  // { path: "/about", loader: () => import("./pages/About.marwa"), layouts: [] },
  // { path: "*", loader: () => import("./pages/404.marwa"), layouts: [] }
];
// End
/* @marwa:routes:end */

createApp()
  .use(createRouter({ routes: __MARWA_ROUTES, history: __MARWA_HISTORY }))
  .mount('#app');
